### ISSUE TITLE
How to use these classes in next.js

### ISSUE THREAD

**Issue by Usama5686** [msnegurski/tailwind-react-datepicker#1]
![Screenshot 2021-07-02 at 5 01 29 AM](https://user-images.githubusercontent.com/66520872/124201863-92840b00-daf2-11eb-86ce-930235004dd8.png)
I am using _**@layer**_  for my utilities where should i use these classes you have used in your project. These classes are not being applied in Next.js

**Comment by msnegurski** [comment]
I think this is because style put in @layer will be purged, and since they are not directly referenced in markup, they are purged. You should probably safelist them https://tailwindcss.com/docs/optimizing-for-production#safelisting-specific-classes
